import React, { useState } from "react";
import { useNavigate } from "react-router-dom";

import {
  Sun,
  Wind,
  Droplets,
  Leaf,
  Zap,
  ArrowRight,
  ChevronRight,
  CheckCircle2,
  X,
  Calculator,
  Activity,
  Home,
  Factory,
  BatteryCharging,
  Globe2,
  TrendingDown,
  Lightbulb,
} from "lucide-react";

const Renewable = () => {
  const navigate = useNavigate();

  // =========================================================
  // STATE
  // =========================================================

  const [selectedEnergy, setSelectedEnergy] = useState(null);

  // =========================================================
  // RENEWABLE ENERGY DATA
  // =========================================================

  const renewableSources = [
    {
      id: 1,
      name: "Solar Energy",
      type: "Solar",
      icon: Sun,
      iconColor: "text-yellow-500",
      iconBg: "bg-yellow-100",
      cardBg: "bg-yellow-50",
      description:
        "Solar energy uses sunlight to generate clean and renewable electricity.",
      longDescription:
        "Solar energy is generated by converting sunlight into electricity using solar panels. It is one of the most accessible renewable energy sources and can be used for homes, businesses and many other applications.",
      benefits: [
        "Uses abundant sunlight",
        "Produces clean electricity",
        "Can reduce dependence on grid electricity",
        "Suitable for rooftops and open areas",
      ],
      examples: [
        "Rooftop solar panels",
        "Solar water heaters",
        "Solar street lights",
        "Solar-powered appliances",
      ],
    },

    {
      id: 2,
      name: "Wind Energy",
      type: "Wind",
      icon: Wind,
      iconColor: "text-cyan-500",
      iconBg: "bg-cyan-100",
      cardBg: "bg-cyan-50",
      description:
        "Wind energy converts the movement of air into electricity using wind turbines.",
      longDescription:
        "Wind energy uses the kinetic energy of moving air. Wind turbines convert this movement into mechanical energy and then electricity. It is a clean renewable source that can support large-scale electricity generation.",
      benefits: [
        "Produces clean electricity",
        "Uses a naturally available resource",
        "Reduces dependence on fossil fuels",
        "Useful for large-scale power generation",
      ],
      examples: [
        "Wind turbines",
        "Wind farms",
        "Small wind generators",
        "Hybrid renewable systems",
      ],
    },

    {
      id: 3,
      name: "Hydro Energy",
      type: "Hydro",
      icon: Droplets,
      iconColor: "text-blue-500",
      iconBg: "bg-blue-100",
      cardBg: "bg-blue-50",
      description:
        "Hydro energy uses flowing or falling water to generate renewable electricity.",
      longDescription:
        "Hydropower generates electricity by using the movement of water. Water flowing through a turbine causes the turbine to rotate, which drives a generator to produce electricity.",
      benefits: [
        "Uses flowing water",
        "Produces renewable electricity",
        "Can provide reliable power",
        "Supports long-term clean energy generation",
      ],
      examples: [
        "Hydroelectric dams",
        "Run-of-river plants",
        "Micro-hydropower",
        "Water turbines",
      ],
    },
  ];

  // =========================================================
  // FUNCTIONS
  // =========================================================

  const openDetails = (energy) => {
    setSelectedEnergy(energy);
  };

  const closeDetails = () => {
    setSelectedEnergy(null);
  };

  const goToCalculator = () => {
    navigate("/calculator");
  };

  const goToTracker = () => {
    navigate("/tracker");
  };

  // =========================================================
  // RETURN
  // =========================================================

  return (
    <div className="min-h-screen bg-[#f8faf9] text-[#102b43]">

      <main className="p-5 md:p-7 lg:p-8">

        {/* ================================================= */}
        {/* HEADER */}
        {/* ================================================= */}

        <section className="rounded-2xl border border-green-100 bg-gradient-to-br from-green-50 via-white to-emerald-50 p-6 shadow-sm md:p-8">

          <div className="flex flex-col gap-7 lg:flex-row lg:items-center lg:justify-between">

            <div className="max-w-3xl">

              <div className="flex items-center gap-2 text-sm font-semibold uppercase tracking-wider text-green-600">

                <Leaf size={17} />

                Renewable Energy

              </div>

              <h1 className="mt-3 text-3xl font-bold tracking-tight text-[#102b43] md:text-4xl lg:text-5xl">
                Clean Energy.
                <br />
                Bright Future.
              </h1>

              <p className="mt-4 max-w-2xl text-sm leading-7 text-slate-500 md:text-base">
                Discover clean and renewable sources of energy
                that can help reduce environmental impact and
                build a more sustainable future.
              </p>

              <div className="mt-6 flex flex-wrap gap-3">

                <button
                  onClick={goToCalculator}
                  className="flex items-center gap-2 rounded-lg bg-green-600 px-5 py-3 text-sm font-semibold text-white shadow-sm transition hover:bg-green-700"
                >
                  <Calculator size={17} />
                  Calculate Savings
                </button>

                <button
                  onClick={goToTracker}
                  className="flex items-center gap-2 rounded-lg border border-green-600 bg-white px-5 py-3 text-sm font-semibold text-green-700 transition hover:bg-green-50"
                >
                  Track Energy
                  <ArrowRight size={17} />
                </button>

              </div>

            </div>


            {/* HERO ICON */}

            <div className="flex justify-center lg:pr-10">

              <div className="relative flex h-48 w-48 items-center justify-center rounded-full bg-green-100 md:h-56 md:w-56">

                <div className="absolute h-36 w-36 rounded-full bg-white shadow-sm md:h-44 md:w-44" />

                <div className="relative flex flex-col items-center">

                  <Sun
                    size={58}
                    className="text-yellow-500"
                  />

                  <Leaf
                    size={40}
                    className="-mt-2 text-green-600"
                  />

                </div>

              </div>

            </div>

          </div>

        </section>


        {/* ================================================= */}
        {/* INTRO STATS */}
        {/* ================================================= */}

        <section className="mt-7 grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">

          <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">

            <div className="flex items-center justify-between">

              <div>
                <p className="text-sm text-slate-500">
                  Clean Sources
                </p>

                <h2 className="mt-1 text-2xl font-bold">
                  3
                </h2>
              </div>

              <div className="flex h-12 w-12 items-center justify-center rounded-full bg-green-100">
                <Leaf
                  size={24}
                  className="text-green-600"
                />
              </div>

            </div>

            <p className="mt-3 text-xs text-slate-400">
              Solar, wind and hydro
            </p>

          </div>


          <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">

            <div className="flex items-center justify-between">

              <div>
                <p className="text-sm text-slate-500">
                  Solar
                </p>

                <h2 className="mt-1 text-2xl font-bold text-yellow-600">
                  Sun
                </h2>
              </div>

              <div className="flex h-12 w-12 items-center justify-center rounded-full bg-yellow-100">
                <Sun
                  size={24}
                  className="text-yellow-500"
                />
              </div>

            </div>

            <p className="mt-3 text-xs text-slate-400">
              Energy from sunlight
            </p>

          </div>


          <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">

            <div className="flex items-center justify-between">

              <div>
                <p className="text-sm text-slate-500">
                  Wind
                </p>

                <h2 className="mt-1 text-2xl font-bold text-cyan-600">
                  Air
                </h2>
              </div>

              <div className="flex h-12 w-12 items-center justify-center rounded-full bg-cyan-100">
                <Wind
                  size={24}
                  className="text-cyan-500"
                />
              </div>

            </div>

            <p className="mt-3 text-xs text-slate-400">
              Energy from moving air
            </p>

          </div>


          <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">

            <div className="flex items-center justify-between">

              <div>
                <p className="text-sm text-slate-500">
                  Hydro
                </p>

                <h2 className="mt-1 text-2xl font-bold text-blue-600">
                  Water
                </h2>
              </div>

              <div className="flex h-12 w-12 items-center justify-center rounded-full bg-blue-100">
                <Droplets
                  size={24}
                  className="text-blue-500"
                />
              </div>

            </div>

            <p className="mt-3 text-xs text-slate-400">
              Energy from flowing water
            </p>

          </div>

        </section>


        {/* ================================================= */}
        {/* ENERGY SOURCES */}
        {/* ================================================= */}

        <section className="mt-8">

          <div className="mb-5">

            <p className="text-sm font-semibold uppercase tracking-wider text-green-600">
              Explore
            </p>

            <h2 className="mt-1 text-2xl font-bold">
              Renewable Energy Sources
            </h2>

            <p className="mt-2 text-sm text-slate-500">
              Learn how different renewable sources can
              contribute to a cleaner energy future.
            </p>

          </div>


          <div className="grid grid-cols-1 gap-5 lg:grid-cols-3">

            {renewableSources.map((energy) => {

              const Icon = energy.icon;

              return (
                <div
                  key={energy.id}
                  className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-md"
                >

                  {/* CARD TOP */}

                  <div className={`p-6 ${energy.cardBg}`}>

                    <div className="flex items-center justify-between">

                      <div
                        className={`flex h-14 w-14 items-center justify-center rounded-full bg-white shadow-sm`}
                      >

                        <Icon
                          size={30}
                          className={energy.iconColor}
                        />

                      </div>

                      <span className="rounded-full bg-white px-3 py-1 text-xs font-semibold text-green-700">
                        Renewable
                      </span>

                    </div>

                    <h3 className="mt-6 text-xl font-bold">
                      {energy.name}
                    </h3>

                  </div>


                  {/* CARD BODY */}

                  <div className="p-6">

                    <p className="text-sm leading-6 text-slate-500">
                      {energy.description}
                    </p>


                    <div className="mt-5 space-y-3">

                      {energy.benefits
                        .slice(0, 3)
                        .map((benefit) => (

                          <div
                            key={benefit}
                            className="flex items-start gap-2"
                          >

                            <CheckCircle2
                              size={17}
                              className="mt-0.5 shrink-0 text-green-600"
                            />

                            <span className="text-sm text-slate-600">
                              {benefit}
                            </span>

                          </div>

                        ))}

                    </div>


                    <button
                      onClick={() =>
                        openDetails(energy)
                      }
                      className="mt-6 flex w-full items-center justify-center gap-2 rounded-lg border border-green-200 bg-green-50 px-4 py-3 text-sm font-semibold text-green-700 transition hover:bg-green-100"
                    >
                      Explore {energy.type}
                      <ChevronRight size={17} />
                    </button>

                  </div>

                </div>
              );
            })}

          </div>

        </section>


        {/* ================================================= */}
        {/* WHY RENEWABLE ENERGY */}
        {/* ================================================= */}

        <section className="mt-8 rounded-2xl bg-[#064d35] p-6 text-white shadow-sm md:p-8">

          <div className="text-center">

            <p className="text-sm font-semibold uppercase tracking-widest text-green-200">
              Why Renewable?
            </p>

            <h2 className="mt-2 text-2xl font-bold md:text-3xl">
              Power a cleaner tomorrow
            </h2>

            <p className="mx-auto mt-3 max-w-2xl text-sm leading-6 text-green-100">
              Renewable energy uses naturally replenished
              resources and can help reduce dependence on
              conventional energy sources.
            </p>

          </div>


          <div className="mt-8 grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-4">

            <div className="rounded-xl border border-white/10 bg-white/10 p-5">

              <Sun
                size={27}
                className="text-yellow-300"
              />

              <h3 className="mt-4 font-bold">
                Clean Power
              </h3>

              <p className="mt-2 text-sm leading-6 text-green-100">
                Generate electricity using renewable natural
                resources.
              </p>

            </div>


            <div className="rounded-xl border border-white/10 bg-white/10 p-5">

              <TrendingDown
                size={27}
                className="text-green-200"
              />

              <h3 className="mt-4 font-bold">
                Lower Impact
              </h3>

              <p className="mt-2 text-sm leading-6 text-green-100">
                Help reduce dependence on fossil-fuel-based
                electricity.
              </p>

            </div>


            <div className="rounded-xl border border-white/10 bg-white/10 p-5">

              <Globe2
                size={27}
                className="text-cyan-300"
              />

              <h3 className="mt-4 font-bold">
                Protect Nature
              </h3>

              <p className="mt-2 text-sm leading-6 text-green-100">
                Support a more sustainable relationship with
                the environment.
              </p>

            </div>


            <div className="rounded-xl border border-white/10 bg-white/10 p-5">

              <BatteryCharging
                size={27}
                className="text-purple-300"
              />

              <h3 className="mt-4 font-bold">
                Energy Future
              </h3>

              <p className="mt-2 text-sm leading-6 text-green-100">
                Explore cleaner technologies for future energy
                needs.
              </p>

            </div>

          </div>

        </section>


        {/* ================================================= */}
        {/* WHERE CAN IT BE USED */}
        {/* ================================================= */}

        <section className="mt-8 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm md:p-8">

          <div className="grid grid-cols-1 gap-8 lg:grid-cols-2 lg:items-center">

            <div>

              <p className="text-sm font-semibold uppercase tracking-wider text-green-600">
                Renewable Applications
              </p>

              <h2 className="mt-2 text-2xl font-bold">
                Renewable energy can be part of everyday life.
              </h2>

              <p className="mt-3 text-sm leading-7 text-slate-500">
                From homes to large facilities, renewable
                technologies can be used in different ways to
                produce and manage cleaner energy.
              </p>


              <div className="mt-6 space-y-4">

                <div className="flex items-start gap-4">

                  <div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full bg-green-100">
                    <Home
                      size={21}
                      className="text-green-600"
                    />
                  </div>

                  <div>
                    <h3 className="font-bold">
                      Homes
                    </h3>

                    <p className="mt-1 text-sm text-slate-500">
                      Rooftop solar panels and solar-powered
                      devices.
                    </p>
                  </div>

                </div>


                <div className="flex items-start gap-4">

                  <div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full bg-blue-100">
                    <Factory
                      size={21}
                      className="text-blue-600"
                    />
                  </div>

                  <div>
                    <h3 className="font-bold">
                      Businesses
                    </h3>

                    <p className="mt-1 text-sm text-slate-500">
                      Renewable electricity for offices,
                      factories and commercial buildings.
                    </p>
                  </div>

                </div>


                <div className="flex items-start gap-4">

                  <div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full bg-yellow-100">
                    <Zap
                      size={21}
                      className="text-yellow-600"
                    />
                  </div>

                  <div>
                    <h3 className="font-bold">
                      Electricity Generation
                    </h3>

                    <p className="mt-1 text-sm text-slate-500">
                      Solar farms, wind farms and hydroelectric
                      power plants.
                    </p>
                  </div>

                </div>

              </div>

            </div>


            {/* RIGHT SIDE */}

            <div className="rounded-2xl bg-green-50 p-6">

              <div className="flex items-center gap-3">

                <div className="flex h-12 w-12 items-center justify-center rounded-full bg-white">
                  <Lightbulb
                    size={24}
                    className="text-green-600"
                  />
                </div>

                <div>
                  <p className="text-xs font-semibold uppercase tracking-wider text-green-600">
                    Eco Insight
                  </p>

                  <h3 className="font-bold text-green-900">
                    Start by understanding your energy use.
                  </h3>
                </div>

              </div>


              <p className="mt-5 text-sm leading-7 text-green-800">
                Before choosing renewable technologies,
                understanding your current electricity
                consumption can help you make better energy
                decisions.
              </p>


              <button
                onClick={goToTracker}
                className="mt-6 flex items-center gap-2 rounded-lg bg-green-600 px-5 py-3 text-sm font-semibold text-white transition hover:bg-green-700"
              >
                Track My Energy
                <ArrowRight size={17} />
              </button>

            </div>

          </div>

        </section>


        {/* ================================================= */}
        {/* BOTTOM CTA */}
        {/* ================================================= */}

        <section className="mt-8 rounded-2xl border border-green-100 bg-gradient-to-r from-green-50 to-white p-6 shadow-sm md:p-8">

          <div className="flex flex-col gap-6 md:flex-row md:items-center md:justify-between">

            <div className="flex items-start gap-4">

              <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-full bg-green-100">

                <Leaf
                  size={25}
                  className="text-green-600"
                />

              </div>

              <div>

                <h2 className="text-xl font-bold md:text-2xl">
                  Ready to make your energy cleaner?
                </h2>

                <p className="mt-2 text-sm text-slate-500">
                  Track your consumption and calculate your
                  potential energy savings.
                </p>

              </div>

            </div>


            <div className="flex flex-wrap gap-3">

              <button
                onClick={goToCalculator}
                className="flex items-center gap-2 rounded-lg border border-green-600 px-5 py-3 text-sm font-semibold text-green-700 transition hover:bg-green-50"
              >
                <Calculator size={17} />
                Calculate
              </button>

              <button
                onClick={goToTracker}
                className="flex items-center gap-2 rounded-lg bg-green-600 px-5 py-3 text-sm font-semibold text-white transition hover:bg-green-700"
              >
                Start Tracking
                <ArrowRight size={17} />
              </button>

            </div>

          </div>

        </section>


        {/* ================================================= */}
        {/* FOOTER TIP */}
        {/* ================================================= */}

        <div className="mt-6 rounded-xl border border-green-100 bg-green-50 p-5">

          <div className="flex items-start gap-3">

            <Lightbulb
              size={21}
              className="mt-0.5 shrink-0 text-green-600"
            />

            <div>

              <p className="font-bold text-green-800">
                EcoTip
              </p>

              <p className="mt-1 text-sm leading-6 text-green-700">
                Renewable energy is one part of sustainable
                living. Combining clean energy with reduced
                consumption makes your energy habits even more
                effective.
              </p>

            </div>

          </div>

        </div>

      </main>


      {/* ================================================= */}
      {/* DETAILS MODAL */}
      {/* ================================================= */}

      {selectedEnergy && (

        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4">

          <div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white shadow-2xl">

            {/* MODAL HEADER */}

            <div className="flex items-start justify-between border-b border-slate-100 p-6">

              <div className="flex items-center gap-4">

                <div
                  className={`flex h-14 w-14 items-center justify-center rounded-full ${selectedEnergy.iconBg}`}
                >

                  {React.createElement(
                    selectedEnergy.icon,
                    {
                      size: 29,
                      className:
                        selectedEnergy.iconColor,
                    }
                  )}

                </div>


                <div>

                  <p className="text-xs font-semibold uppercase tracking-wider text-green-600">
                    Renewable Energy
                  </p>

                  <h2 className="mt-1 text-2xl font-bold">
                    {selectedEnergy.name}
                  </h2>

                </div>

              </div>


              <button
                onClick={closeDetails}
                className="rounded-full p-2 text-slate-400 transition hover:bg-slate-100 hover:text-slate-700"
              >
                <X size={21} />
              </button>

            </div>


            {/* MODAL BODY */}

            <div className="p-6">

              <p className="text-sm leading-7 text-slate-600">
                {selectedEnergy.longDescription}
              </p>


              {/* BENEFITS */}

              <div className="mt-7">

                <h3 className="text-lg font-bold">
                  Key Benefits
                </h3>

                <div className="mt-4 grid grid-cols-1 gap-3 sm:grid-cols-2">

                  {selectedEnergy.benefits.map(
                    (benefit) => (

                      <div
                        key={benefit}
                        className="flex items-start gap-3 rounded-xl bg-green-50 p-4"
                      >

                        <CheckCircle2
                          size={18}
                          className="mt-0.5 shrink-0 text-green-600"
                        />

                        <p className="text-sm text-green-800">
                          {benefit}
                        </p>

                      </div>

                    )
                  )}

                </div>

              </div>


              {/* EXAMPLES */}

              <div className="mt-7">

                <h3 className="text-lg font-bold">
                  Examples
                </h3>

                <div className="mt-4 grid grid-cols-1 gap-3 sm:grid-cols-2">

                  {selectedEnergy.examples.map(
                    (example) => (

                      <div
                        key={example}
                        className="rounded-xl border border-slate-200 p-4"
                      >

                        <div className="flex items-center gap-3">

                          <div className="flex h-9 w-9 items-center justify-center rounded-full bg-slate-50">

                            <Zap
                              size={17}
                              className="text-green-600"
                            />

                          </div>

                          <p className="text-sm font-semibold text-slate-700">
                            {example}
                          </p>

                        </div>

                      </div>

                    )
                  )}

                </div>

              </div>


              {/* MODAL BUTTONS */}

              <div className="mt-8 flex flex-wrap justify-end gap-3">

                <button
                  onClick={closeDetails}
                  className="rounded-lg border border-slate-200 px-5 py-3 text-sm font-semibold text-slate-600 transition hover:bg-slate-50"
                >
                  Close
                </button>

                <button
                  onClick={() => {
                    closeDetails();
                    goToCalculator();
                  }}
                  className="flex items-center gap-2 rounded-lg bg-green-600 px-5 py-3 text-sm font-semibold text-white transition hover:bg-green-700"
                >
                  <Calculator size={17} />
                  Calculate Savings
                </button>

              </div>

            </div>

          </div>

        </div>

      )}

    </div>
  );
};

export default Renewable;